# Black Configuration
[tool.black]
line-length = 100
target-version = ["py313"] # Python Version
skip-string-normalization = true  # do not change quotes ' -> "
exclude = '''
/(
    \.git
  | \.venv
  | env
  | build
  | dist
  | migrations
  | __pycache__
  | \.env
  | \.editorconfig
  | \.idea
  | \.vscode
  | \.pytest_cache
  | requirements.txt
)/
'''

# Isort Configuration
[tool.isort]
profile = "black" # Use black profile
line_length = 100 # Same as black
known_third_party = ["aiogram", "aiohttp", "python_dotenv"] # Third Party Libraries
known_first_party = ["army-doc-gen"]  # Project Folder
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]  # Normal order of imports
